version: '2'
services:
  dnsmasq:
    restart: always
    container_name: dnsmasq
    image: gsvitins/dnsmasq:1.0
    command: --log-queries --log-facility=/var/log/dnsmasq.log
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./logs/:/var/log/
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"

