version: '2'
services:
  dnsmasq:
    restart: always
    container_name: dnsmasq
    image: gsvitins/dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53/tcp:53/tcp"
      - "53/udp:53/udp"
      - "67/udp:67/udp"

